version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - NEO4J_URI=$NEO4J_URI
      - NEO4J_USERNAME=$NEO4J_USERNAME
      - NEO4J_PASSWORD=$NEO4J_PASSWORD
      - NEO4J_DB_NAME=$NEO4J_DB_NAME
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
  neo4j:
    image: neo4j:5.18-enterprise
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_conf:/conf
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1" ]
      interval: 15s
      timeout: 30s
      retries: 10
volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_conf:
